   
import java.awt.Button;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author RALC
 */
public class Principal extends javax.swing.JFrame {

    public JButton[][] tablero = new JButton[8][8];//Es un señuelo
    public Piezas[][] tablero_principal = new Piezas[8][8];//aqui trabajeromos
    public int[][] pos = new int[16][16];
    public boolean turno1;
    public String jugador1;
    public String jugador2;
    public int mov1;
    public int mov2;
    public boolean clic;//este me dice si una pieza tiene clic o no--true; está seleccionando, false--moverá pieza
    public int[] pieza_mover = new int[2];
    public int [] rey_blanco = new int[2];
    public int [] rey_negro = new int[2];

    public JButton[][] getTablero() {
        return tablero;
    }

    public void setTablero(JButton[][] tablero) {
        this.tablero = tablero;
    }

    public Piezas[][] getTablero_principal() {
        return tablero_principal;
    }

    public void setTablero_principal(Piezas[][] tablero_principal) {
        this.tablero_principal = tablero_principal;
    }

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        tablerito();

    }
    //ArrayList<JButton>  tablero = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_jugador1 = new javax.swing.JLabel();
        jl_jugador2 = new javax.swing.JLabel();
        tf_jugador1 = new javax.swing.JTextField();
        tf_jugador2 = new javax.swing.JTextField();
        imagen_entrada = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_jugador1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_jugador1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jl_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 20));

        jl_jugador2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_jugador2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jl_jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 70, 20));

        tf_jugador1.setEditable(false);
        jPanel1.add(tf_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 58, 67, -1));

        tf_jugador2.setEditable(false);
        jPanel1.add(tf_jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 58, 70, -1));

        imagen_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagen_entradaActionPerformed(evt);
            }
        });
        jPanel1.add(imagen_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 129, 60));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 40, 40));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 40, 40));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 40, 40));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 40, 40));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 40, 40));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 40, 40));

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 40, 40));

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 40, 40));

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, 40));

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 40, 40));

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 40, 40));

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 40, 40));

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 40, 40));

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 40, 40));

        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 40, 40));

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 40, 40));

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 40, 40));

        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 40, 40));

        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 40, 40));

        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 40, 40));

        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 40, 40));

        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 40, 40));

        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 40, 40));

        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 40, 40));

        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 40, 40));

        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 40, 40));

        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 40, 40));

        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 40, 40));

        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 40, 40));

        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 40, 40));

        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 40, 40));

        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 40, 40));

        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 40, 40));

        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 40, 40));

        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 40, 40));

        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 40, 40));

        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 40, 40));

        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 40, 40));

        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 40, 40));

        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 40, 40));

        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 40, 40));

        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 40, 40));

        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 40, 40));

        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 40, 40));

        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 40, 40));

        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 40, 40));

        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 40, 40));

        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 40, 40));

        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 40, 40));

        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 40, 40));

        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 40, 40));

        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 40, 40));

        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 40, 40));

        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 40, 40));

        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 40, 40));

        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 40, 40));

        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 40, 40));

        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 40, 40));

        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 40, 40));

        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 40, 40));

        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 40, 40));

        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 40, 40));

        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 40, 40));

        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 544));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void botones() {
        tablero[0][0] = (this.jButton1);
        tablero[0][1] = (this.jButton2);
        tablero[0][2] = (this.jButton3);
        tablero[0][3] = (this.jButton4);
        tablero[0][4] = (this.jButton5);
        tablero[0][5] = (this.jButton6);
        tablero[0][6] = (this.jButton7);
        tablero[0][7] = (this.jButton8);
        tablero[1][0] = (this.jButton9);
        tablero[1][1] = (this.jButton10);
        tablero[1][2] = (this.jButton11);
        tablero[1][3] = (this.jButton12);
        tablero[1][4] = (this.jButton13);
        tablero[1][5] = (this.jButton14);
        tablero[1][6] = (this.jButton15);
        tablero[1][7] = (this.jButton16);
        tablero[2][0] = (this.jButton17);
        tablero[2][1] = (this.jButton18);
        tablero[2][2] = (this.jButton19);
        tablero[2][3] = (this.jButton20);
        tablero[2][4] = (this.jButton21);
        tablero[2][5] = (this.jButton22);
        tablero[2][6] = (this.jButton23);
        tablero[2][7] = (this.jButton24);
        tablero[3][0] = (this.jButton25);
        tablero[3][1] = (this.jButton26);
        tablero[3][2] = (this.jButton27);
        tablero[3][3] = (this.jButton28);
        tablero[3][4] = (this.jButton29);
        tablero[3][5] = (this.jButton30);
        tablero[3][6] = (this.jButton31);
        tablero[3][7] = (this.jButton32);
        tablero[4][0] = (this.jButton33);
        tablero[4][1] = (this.jButton34);
        tablero[4][2] = (this.jButton35);
        tablero[4][3] = (this.jButton36);
        tablero[4][4] = (this.jButton37);
        tablero[4][5] = (this.jButton38);
        tablero[4][6] = (this.jButton39);
        tablero[4][7] = (this.jButton40); //
        tablero[5][0] = (this.jButton41);
        tablero[5][1] = (this.jButton42);
        tablero[5][2] = (this.jButton43);
        tablero[5][3] = (this.jButton44);
        tablero[5][4] = (this.jButton45);
        tablero[5][5] = (this.jButton46);
        tablero[5][6] = (this.jButton47);
        tablero[5][7] = (this.jButton48);
        tablero[6][0] = (this.jButton49);
        tablero[6][1] = (this.jButton50); //
        tablero[6][2] = (this.jButton51);
        tablero[6][3] = (this.jButton52);
        tablero[6][4] = (this.jButton53);
        tablero[6][5] = (this.jButton54);
        tablero[6][6] = (this.jButton55);
        tablero[6][7] = (this.jButton56);
        tablero[7][0] = (this.jButton57);
        tablero[7][1] = (this.jButton58);
        tablero[7][2] = (this.jButton59);
        tablero[7][3] = (this.jButton60); //
        tablero[7][4] = (this.jButton61);
        tablero[7][5] = (this.jButton62);
        tablero[7][6] = (this.jButton63);
        tablero[7][7] = (this.jButton64);

    }

    public void tablerito() {
        clic = true;
        turno1 = true;
        mov1 = 0;
        tf_jugador1.setText(mov1 + "");
        mov2 = 0;
        tf_jugador2.setText(mov2 + "");
        try {
            jl_jugador1.setText(JOptionPane.showInputDialog("Ingrese el nombre del jugador 1").toUpperCase());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No te irás sin ver el ajedrez");
        }
        try {
            jl_jugador2.setText(JOptionPane.showInputDialog("Ingrese el nombre del jugador 2").toUpperCase());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No te irás sin ver el ajedrez");
        }
        if ("".equals(jl_jugador1.getText())) {
            jl_jugador1.setText("Jugador 1");
        }
        if ("".equals(jl_jugador2.getText())) {
            jl_jugador2.setText("Jugador 2");
        }

        botones();
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {

                tablero[i][j].setBackground(Color.white);
                if (i == 1) {//peones blancos
                    //tablero.get(i).setBackground(Color.yellow);
                    //tablero[i][j].setText("♟");//negors

                    tablero_principal[i][j] = new Peon(false);//negras
                    tablero[i][j].setText(tablero_principal[i][j].toString());

                    //System.out.println("♟");
                }
                if (i == 6) {//peones negros
                    //tablero.get(i).setBackground(Color.yellow);
                    //tablero[i][j].setText("♙");//blanco
                    tablero_principal[i][j] = new Peon(true);//blancas
                    tablero[i][j].setText(tablero_principal[i][j].toString());

                }
            }
        }
        tablero_principal[0][0] = new Torres(false);
        tablero_principal[0][1] = new Caballo(false);
        tablero_principal[0][2] = new Alfin(false);
        tablero_principal[0][3] = new Rey(false);
        tablero_principal[0][4] = new Reina(false);
        tablero_principal[0][5] = new Alfin(false);
        tablero_principal[0][6] = new Caballo(false);
        tablero_principal[0][7] = new Torres(false);
        //botones
//        tablero[0][0].setText("♜");//negras
//        tablero[0][1].setText("♞");
//        tablero[0][2].setText("♝");
//        tablero[0][3].setText("♛");
//        tablero[0][4].setText("♚");
//        tablero[0][5].setText("♝");
//        tablero[0][6].setText("♞");
//        tablero[0][7].setText("♜");

//        tablero[7][0].setText("♖");//blancas
//        tablero[7][1].setText("♘");
//        tablero[7][2].setText("♗");
//        tablero[7][3].setText("♕");
//        tablero[7][4].setText("♔");
//        tablero[7][5].setText("♗");
//        tablero[7][6].setText("♘");
//        tablero[7][7].setText("♖");
        //blancas 
        tablero_principal[7][0] = new Torres(true);
        tablero_principal[7][1] = new Caballo(true);
        tablero_principal[7][2] = new Alfin(true);
        tablero_principal[7][3] = new Rey(true);
        tablero_principal[7][4] = new Reina(true);
        tablero_principal[7][5] = new Alfin(true);
        tablero_principal[7][6] = new Caballo(true);
        tablero_principal[7][7] = new Torres(true);

        colorear();

    }

    public void principal(int x, int y) {
        if (clic) {
            pieza_mover[0] = x;
            pieza_mover[1] = y;
            //int[][] pos = new int[16][16];
            colorear();
            int ban = 0;
            String boton = tablero[x][y].getText();
            if ("".equals(boton)) {
                JOptionPane.showMessageDialog(this, "No hay piezas en esa "
                        + "posición del tablero\nSeleccione otra posición");
                tablero[x][y].setBackground(Color.red);
            } else {
                if (turno1) {//jugador1
                    switch (boton) {
                        case "♖"://blancas---torre
                            pos = new int[4][16];
                            pos = ((Torres) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♘"://caballo
                            pos = new int[8][2];
                            pos = ((Caballo) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♗"://alfin
                            pos = new int[4][16];
                            pos = ((Alfin) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♕"://rey
                            pos = new int[4][16];
                            pos = ((Rey) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♔"://reina
                            pos = new int[4][16];
                            pos = ((Reina) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♙"://peon
                            pos = new int[0][12];
                            pos = ((Peon) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        default:
                            tablero[x][y].setBackground(Color.red);
                            //turno1 = !turno1;
                            JOptionPane.showMessageDialog(this, "La pieza que seleccionaste "
                                    + "no es tuya\nEscoge otra");
                            ban = 1;
                    }
                } else {//turno de jugador2
                    switch (boton) {
                        case "♜"://negras---torre
                            pos = new int[4][16];
                            pos = ((Torres) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♞"://caballo
                            pos = new int[8][2];
                            pos = ((Caballo) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♝"://alfin
                            pos = new int[4][16];
                            pos = ((Alfin) tablero_principal[x][y]).movimiento(x, y, tablero_principal);

                            break;
                        case "♛"://rey
                            pos = new int[4][16];
                            pos = ((Rey) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♚"://reina
                            pos = new int[4][16];
                            pos = ((Reina) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        case "♟"://peon
                            pos = new int[0][12];
                            pos = ((Peon) tablero_principal[x][y]).movimiento(x, y, tablero_principal);
                            break;
                        default:
                            tablero[x][y].setBackground(Color.red);
                           // turno1 = !turno1;
                            JOptionPane.showMessageDialog(this, "La pieza que seleccionaste "
                                    + "no es tuya\nEscoge otra");
                            ban = 1;
                    }
                }
                if (ban == 0) {
                    //System.out.println(Arrays.deepToString(pos));
                    int error = 0;
                    for (int i = 0; i < pos.length; i++) {
                        for (int j = 0; j < pos[i].length; j += 2) {
                            int f = pos[i][j];
                            int c = pos[i][j + 1];
                            if (f != -1 && c != -1) {
                                tablero[f][c].setBackground(Color.GREEN);
                                error = 1;
                            }
                        }
                    }
                    if (error == 0) {
                        JOptionPane.showMessageDialog(this, "La pieza que escogió no puede moverse\n"
                                + "Escoja otra");
                    }else{
                        int seg = JOptionPane.showConfirmDialog(this, "Está seguro que desea mover esa pieza");
                    if (seg != 0) {
                        colorear();
                        JOptionPane.showMessageDialog(this, "Escoja otra pieza");
                    } else {
                        clic = !clic;
                    }
                    }
                } else {
                    ban = 0;
                }
            }

        } else {//si tiene presionado clic, significa que estará moviendo
            boolean acceso = false;
            for (int i = 0; i < pos.length; i++) {
                for (int j = 0; j < pos[i].length; j += 2) {
                    if ((pos[i][j] == x) && (pos[i][j + 1] == y)) {
                        acceso = true;
                        break;
                    }
                }
            }
            if (acceso) {
              //  if (tablero_principal[x][y] == null) {
                    if (tablero_principal[pieza_mover[0]][pieza_mover[1]] instanceof Peon) {
                        tablero_principal[x][y] = new Peon(turno1);
                        
                    }
                    if (tablero_principal[pieza_mover[0]][pieza_mover[1]] instanceof Torres) {
                        tablero_principal[x][y] = new Torres(turno1);
                    }
                    if (tablero_principal[pieza_mover[0]][pieza_mover[1]] instanceof Caballo) {
                        tablero_principal[x][y] = new Caballo(turno1);
                    }
                    if (tablero_principal[pieza_mover[0]][pieza_mover[1]] instanceof Alfin) {
                        tablero_principal[x][y] = new Alfin(turno1);
                    }
                    if (tablero_principal[pieza_mover[0]][pieza_mover[1]] instanceof Reina) {
                        tablero_principal[x][y] = new Reina(turno1);
                    }
                    if (tablero_principal[pieza_mover[0]][pieza_mover[1]] instanceof Rey) {
                        tablero_principal[x][y] = new Rey(turno1);
                    }
                //}
                if (turno1) {
                        mov1++;
                    } else {
                        mov2++;
                    }
                clic = !clic;
                turno1 = !turno1;
                boolean temp;//así guardo el tueno en el que estaba   
                tablero_principal[pieza_mover[0]][pieza_mover[1]] = null;
                colorear();
                //AQUI VAMOS A TRABAJAR AHORITA
                pos = tablero_principal[x][y].movimiento(x, y, tablero_principal);
                if (rey_blanco[0] < rey_negro[0]) {
                    temp = true;
                }else if(rey_blanco[0] > rey_negro[0]){
                    temp = false;
                }else{
                    if (rey_blanco[1] < rey_negro[1]) {
                        temp = true;
                    }else{
                        temp = false;
                    }
                }
                
                for (int i = 0; i < pos.length; i++) {
                    for (int j = 0; j < pos[i].length; j+=2) {
                        if (temp) {
                            if (pos[i][j]==rey_negro[0] && pos[i][j+1]==rey_negro[1]) {
                                    JOptionPane.showMessageDialog(this, "El rey de las piezas negras está en jaque");
                                
                            }
                        }else{
                            if (pos[i][j]==rey_blanco[0] && pos[i][j+1]==rey_blanco[1]) {
                                    JOptionPane.showMessageDialog(this, "El rey de las piezas blancas está en jaque");
                                
                            }
                        }
                    }
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "La pieza no se debe mover a esa posición\n"
                        + "Solo a los cuadros rellenos de verde");
            }
        }

    }

    public void colorear() {
        boolean col = true;
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                if (i % 2 == 0) {
                    if (col) {
                        tablero[i][j].setBackground(Color.YELLOW);
                        col = !col;
                    } else {
                        tablero[i][j].setBackground(Color.white);
                        col = !col;
                    }
                } else {
                    if (!col) {
                        tablero[i][j].setBackground(Color.YELLOW);
                        col = !col;
                    } else {
                        tablero[i][j].setBackground(Color.white);
                        col = !col;
                    }
                }
                try {
                    tablero[i][j].setText(tablero_principal[i][j].toString());//me quede imprimiendo el tablero
                } catch (Exception e) {
                    tablero[i][j].setText("");
                    //tablero[0][3].setText("♕");

                }
                if (tablero_principal[i][j] instanceof Rey) {
                    if (turno1) {
                        rey_blanco[0] = i;
                        rey_blanco[1] = j;
                    }else{
                        rey_negro[0] = i;
                        rey_negro[1] = j;
                    }
                }
            }
            System.out.println(Arrays.toString(rey_blanco));
            System.out.println(Arrays.toString(rey_negro));
        }

        tf_jugador1.setText(mov1 + "");
        tf_jugador2.setText(mov2 + "");
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        principal(0, 0);
        //System.out.println(tablero.get(0).getClass().toString());


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        principal(0, 1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        principal(0, 2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        principal(0, 3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        principal(0, 4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        principal(0, 5);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        principal(0, 6);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        principal(0, 7);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        principal(1, 0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        principal(1, 1);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        principal(1, 2);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        principal(1, 3);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        principal(1, 4);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        principal(1, 5);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        principal(1, 6);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        principal(1, 7);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        principal(2, 0);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        principal(2, 1);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        principal(2, 2);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        principal(2, 3);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        principal(2, 4);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        principal(2, 5);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        principal(2, 6);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        principal(2, 7);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        principal(3, 0);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        principal(3, 1);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        principal(3, 2);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        principal(3, 3);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        principal(3, 4);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        principal(3, 5);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        principal(3, 6);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        principal(3, 7);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        principal(4, 0);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        principal(4, 1);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        principal(4, 2);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        principal(4, 3);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        principal(4, 4);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        principal(4, 5);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        principal(4, 6);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        principal(4, 7);
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        principal(5, 0);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        principal(5, 1);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        principal(5, 2);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        principal(5, 3);
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        principal(5, 4);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        principal(5, 5);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        principal(5, 6);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        principal(5, 7);
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        principal(6, 0);
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        principal(6, 1);
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        principal(6, 2);
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        principal(6, 3);
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        principal(6, 4);
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        principal(6, 5);
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        principal(6, 6);
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        principal(6, 7);
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        principal(7, 0);
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        principal(7, 1);
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        principal(7, 2);
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        principal(7, 3);
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        principal(7, 4);
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        principal(7, 5);
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        principal(7, 6);
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        principal(7, 7);
    }//GEN-LAST:event_jButton64ActionPerformed

    private void imagen_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagen_entradaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir") == 0) {
            JOptionPane.showMessageDialog(this, "Nos Vemos");
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this, "Seguí jugando");
        }

    }//GEN-LAST:event_imagen_entradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imagen_entrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_jugador1;
    private javax.swing.JLabel jl_jugador2;
    private javax.swing.JTextField tf_jugador1;
    private javax.swing.JTextField tf_jugador2;
    // End of variables declaration//GEN-END:variables
}
